### ISSUE TITLE
Add documentation to all the files

### ISSUE THREAD

**Issue by misha1235000** [misha1235000/serverRegisterClient#5]
### Todo:
Add documentation to all the files:

**Login Component**
- [x] login.component.ts
- [x] login.service.ts

**Open Register Component**
- [x] open-register.component.ts

**Shared**
- [x] shared.ts

**Sidenav Component**
- [x] sidenav.component.ts
- [x] sidenav.service.ts

**Tokens Component**
- [x] tokens.component.ts

**Toolbar Component**
- [x] toolbar.component.ts
